import { useState, useEffect, useRef } from 'react';
import { useParams } from 'react-router-dom';
import { Download, FileText, Image as ImageIcon, BarChart3 } from 'lucide-react';
import { getTeams } from '../services/teamService';
import { getTournament } from '../services/tournamentService';
import { useToast } from '../components/Toast';

export default function Standings() {
    const { tournamentId } = useParams();
    const addToastMsg = useToast();
    const [teams, setTeams] = useState([]);
    const [tournament, setTournament] = useState(null);
    const [loading, setLoading] = useState(true);
    const tableRef = useRef(null);

    useEffect(() => { loadData(); }, [tournamentId]);

    async function loadData() {
        try {
            const [t, te] = await Promise.all([
                getTournament(tournamentId),
                getTeams(tournamentId),
            ]);
            setTournament(t);
            // Sort: points desc → GD desc → GF desc
            te.sort((a, b) =>
                (b.points || 0) - (a.points || 0) ||
                (b.goalDifference || 0) - (a.goalDifference || 0) ||
                (b.goalsFor || 0) - (a.goalsFor || 0)
            );
            setTeams(te);
        } catch (e) {
            console.error(e);
        }
        setLoading(false);
    }

    // CSV Export
    function exportCSV() {
        const headers = ['#', 'Team', 'M', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts'];
        const rows = teams.map((t, i) => [
            i + 1, t.name, t.matches || 0, t.wins || 0, t.draws || 0, t.losses || 0,
            t.goalsFor || 0, t.goalsAgainst || 0, t.goalDifference || 0, t.points || 0
        ]);
        const csv = [headers, ...rows].map(r => r.join(',')).join('\n');
        const blob = new Blob([csv], { type: 'text/csv' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${tournament?.name || 'standings'}_standings.csv`;
        a.click();
        URL.revokeObjectURL(url);
        addToastMsg('CSV downloaded');
    }

    // PDF Export
    async function exportPDF() {
        try {
            const { jsPDF } = await import('jspdf');
            const autoTable = (await import('jspdf-autotable')).default;
            const doc = new jsPDF();

            doc.setFontSize(18);
            doc.setTextColor(56, 189, 248);
            doc.text(tournament?.name || 'Standings', 14, 22);
            doc.setFontSize(10);
            doc.setTextColor(150, 150, 150);
            doc.text('Generated by TournamentOS', 14, 30);

            autoTable(doc, {
                startY: 38,
                head: [['#', 'Team', 'M', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts']],
                body: teams.map((t, i) => [
                    i + 1, t.name, t.matches || 0, t.wins || 0, t.draws || 0, t.losses || 0,
                    t.goalsFor || 0, t.goalsAgainst || 0, t.goalDifference || 0, t.points || 0
                ]),
                theme: 'grid',
                headStyles: { fillColor: [15, 22, 41], textColor: [56, 189, 248], fontStyle: 'bold' },
                bodyStyles: { fillColor: [21, 29, 54], textColor: [226, 232, 240] },
                alternateRowStyles: { fillColor: [15, 22, 41] },
                styles: { fontSize: 9, cellPadding: 4 },
            });

            doc.save(`${tournament?.name || 'standings'}_standings.pdf`);
            addToastMsg('PDF downloaded');
        } catch (e) {
            addToastMsg('Error generating PDF', 'error');
        }
    }

    // Image Export
    async function exportImage() {
        try {
            const { toPng } = await import('html-to-image');
            if (!tableRef.current) return;
            const dataUrl = await toPng(tableRef.current, {
                backgroundColor: '#0a0e1a',
                pixelRatio: 2,
            });
            const a = document.createElement('a');
            a.href = dataUrl;
            a.download = `${tournament?.name || 'standings'}_standings.png`;
            a.click();
            addToastMsg('Image downloaded');
        } catch (e) {
            addToastMsg('Error generating image', 'error');
        }
    }

    if (loading) {
        return (
            <div className="flex items-center justify-center py-20">
                <div className="w-8 h-8 border-2 border-[var(--color-accent-400)] border-t-transparent rounded-full animate-spin" />
            </div>
        );
    }

    return (
        <div className="space-y-6 animate-fade-in">
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
                <div>
                    <h1 className="text-2xl font-bold text-white">Standings</h1>
                    <p className="text-slate-400 text-sm mt-1">{tournament?.name || 'Tournament'} points table</p>
                </div>
                <div className="flex gap-2">
                    <button
                        onClick={exportCSV}
                        className="inline-flex items-center gap-1.5 px-3 py-2 rounded-xl bg-[var(--color-dark-700)] border border-[var(--color-dark-500)] text-sm text-slate-300 hover:text-white hover:border-[var(--color-accent-400)]/30 transition-all"
                    >
                        <Download size={14} /> CSV
                    </button>
                    <button
                        onClick={exportPDF}
                        className="inline-flex items-center gap-1.5 px-3 py-2 rounded-xl bg-[var(--color-dark-700)] border border-[var(--color-dark-500)] text-sm text-slate-300 hover:text-white hover:border-[var(--color-accent-400)]/30 transition-all"
                    >
                        <FileText size={14} /> PDF
                    </button>
                    <button
                        onClick={exportImage}
                        className="inline-flex items-center gap-1.5 px-3 py-2 rounded-xl bg-[var(--color-dark-700)] border border-[var(--color-dark-500)] text-sm text-slate-300 hover:text-white hover:border-[var(--color-accent-400)]/30 transition-all"
                    >
                        <ImageIcon size={14} /> Image
                    </button>
                </div>
            </div>

            {teams.length === 0 ? (
                <div className="text-center py-16 glass-card">
                    <BarChart3 size={48} className="mx-auto text-slate-600 mb-4" />
                    <p className="text-lg font-semibold text-slate-400">No teams yet</p>
                    <p className="text-sm text-slate-500 mt-1">Add teams and play matches to see standings</p>
                </div>
            ) : (
                <div className="glass-card overflow-hidden" ref={tableRef}>
                    <div className="p-4 border-b border-[var(--color-dark-600)]">
                        <h3 className="text-base font-bold text-white">{tournament?.name} — Points Table</h3>
                    </div>
                    <div className="overflow-x-auto">
                        <table className="w-full standings-table">
                            <thead>
                                <tr>
                                    <th className="rounded-none">#</th>
                                    <th className="text-left rounded-none">Team</th>
                                    <th className="rounded-none">M</th>
                                    <th className="rounded-none">W</th>
                                    <th className="rounded-none">D</th>
                                    <th className="rounded-none">L</th>
                                    <th className="rounded-none">GF</th>
                                    <th className="rounded-none">GA</th>
                                    <th className="rounded-none">GD</th>
                                    <th className="rounded-none">Pts</th>
                                </tr>
                            </thead>
                            <tbody>
                                {teams.map((t, i) => (
                                    <tr key={t.id} className={`animate-fade-in-up delay-${Math.min(i + 1, 6)}`}>
                                        <td>
                                            <span className={`inline-flex items-center justify-center w-6 h-6 rounded-full text-xs font-bold ${i === 0 ? 'bg-amber-400/20 text-amber-400' :
                                                    i === 1 ? 'bg-slate-300/20 text-slate-300' :
                                                        i === 2 ? 'bg-orange-400/20 text-orange-400' :
                                                            'text-slate-500'
                                                }`}>
                                                {i + 1}
                                            </span>
                                        </td>
                                        <td className="text-left">
                                            <div className="flex items-center gap-2">
                                                <div className="w-7 h-7 rounded-lg bg-gradient-to-br from-[var(--color-accent-400)]/20 to-purple-500/20 flex items-center justify-center text-xs font-bold text-[var(--color-accent-400)]">
                                                    {t.logo ? (
                                                        <img src={t.logo} alt="" className="w-full h-full object-cover rounded-lg" />
                                                    ) : (
                                                        t.name?.[0]?.toUpperCase()
                                                    )}
                                                </div>
                                                <span className="font-semibold text-white">{t.name}</span>
                                            </div>
                                        </td>
                                        <td>{t.matches || 0}</td>
                                        <td className="text-emerald-400 font-semibold">{t.wins || 0}</td>
                                        <td className="text-amber-400">{t.draws || 0}</td>
                                        <td className="text-red-400">{t.losses || 0}</td>
                                        <td>{t.goalsFor || 0}</td>
                                        <td>{t.goalsAgainst || 0}</td>
                                        <td className={`font-semibold ${(t.goalDifference || 0) > 0 ? 'text-emerald-400' : (t.goalDifference || 0) < 0 ? 'text-red-400' : ''}`}>
                                            {(t.goalDifference || 0) > 0 ? '+' : ''}{t.goalDifference || 0}
                                        </td>
                                        <td>
                                            <span className="inline-flex items-center justify-center min-w-[28px] px-2 py-1 rounded-lg bg-[var(--color-accent-400)]/10 text-[var(--color-accent-400)] font-bold text-sm">
                                                {t.points || 0}
                                            </span>
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </div>
            )}
        </div>
    );
}
